# Generated by Django 3.2.6 on 2021-11-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMS_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Don_Nghi_Phep',
        ),
    ]
